// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeoklsspynwktggvrrcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lb2tsc3NweW53a3RnZ3ZycmNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzg5MjYsImV4cCI6MjA1NjkxNDkyNn0.dLYGPxN31HA4GFc-LNWfa_GmjgnJE32FCbNcr9xP3u8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);